{% set name = "scisave" %}
{% set version = "1.4.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scisave-{{ version }}.tar.gz
  sha256: b6dc22e0cb380bd49eebb66d9d9f4be71406c2b0d3cf66b964b2c5d6195c489c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.5
    - wheel >=0.45
    - setuptools-scm >=8.1
    - pip >=24.3
  run:
    - python >={{ python_min }}
    - pyyaml >=6.0
    - numpy >=1.24

test:
  imports:
    - scisave
  requires:
    - python {{ python_min }}
    - pip >=24.3

about:
  summary: SciSave - Serialization for Scientific Data
  description: |
    SciSave is a Python serialization/deserialization module. Specially 
    targeted for scientific applications. Load JSON/YAML configuration files. 
    Load and write JSON/Pickle data files. Define custom YAML extensions 
    (path handling, includes, env variables, etc.). Define custom JSON 
    extensions (complex numbers and numpy arrays).
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/scisave
  dev_url: https://github.com/otvam/scisave
  home: https://github.com/otvam/scisave

extra:
  recipe-maintainers:
    - otvam
