{% set name = "scisave" %}
{% set version = "1.4.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scisave-{{ version }}.tar.gz
  sha256: 57e5b234c73897eccd990255eda5d50a55015b50aab9aa1a9f52e58c0c7788e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.2
    - wheel >=0.41
    - setuptools-scm >=7.1
    - pip >=24.2
  run:
    - python >={{ python_min }}
    - pyyaml >=6.0
    - numpy >=1.24

test:
  imports:
    - scisave
  requires:
    - pip

about:
  summary: SciSave - Python Data Loader/Dumper for Science
  description: |
    SciSave is a Python serialization/deserialization module. Specially 
    targeted for scientific applications. Load JSON/YAML configuration files. 
    Load and write JSON/Pickle data files. Define custom YAML extensions 
    (path handling, includes, and environment variables). Define custom JSON 
    extensions (complex numbers and numpy array).
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/scisave
  dev_url: https://github.com/otvam/scisave
  home: https://github.com/otvam/scisave

extra:
  recipe-maintainers:
    - otvam
