{% set name = "scisave" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scisave-{{ version }}.tar.gz
  sha256: e7aebcd3b93c363f40bf0d4372e529fe060f1001b41530efacce377d767706a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >68.2
    - wheel >0.41
    - setuptools-scm >7.1
    - pip
  run:
    - python >=3.9
    - pyyaml >=6.0
    - numpy >=1.24

test:
  imports:
    - scisave
  requires:
    - pip

about:
  summary: SciSave - Python Data Loader/Dumper for Science
  description: |
    SciSave is a Python serialization/deserialization module. Specially 
    targeted for scientific applications. Load JSON/YAML configuration files. 
    Load and write JSON/Pickle data files. Define custom YAML extensions 
    (path handling, includes, and environment variables). Define custom JSON 
    extensions (complex numbers and numpy array).
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/scisave
  dev_url: https://github.com/otvam/scisave
  home: https://github.com/otvam/scisave

extra:
  recipe-maintainers:
    - otvam
