{% set name = "scisave" %}
{% set version = "1.5.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scisave-{{ version }}.tar.gz
  sha256: b15eacc9014294233a1d3ccd172206f48d069a81c6346d28863596e7a27f5e31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.5
    - wheel >=0.45
    - setuptools-scm >=8.1
    - pip >=24.3
  run:
    - python >={{ python_min }}
    - jsonschema >=4.23.0
    - pyyaml >=6.0
    - numpy >=1.24

test:
  imports:
    - scisave
  requires:
    - python {{ python_min }}
    - pip >=24.3

about:
  summary: SciSave - Serialization for Scientific Data
  description: |
    SciSave is a Python serialization/deserialization module. Specially 
    targeted for scientific applications. Load JSON/YAML configuration files. 
    Load and write JSON/Pickle data files. Validate data with JSON schemas.
    Define custom YAML extensions (path handling, includes, env variables, etc.).
    Define custom JSON extensions (complex numbers and numpy arrays).
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/scisave
  dev_url: https://github.com/otvam/scisave
  home: https://github.com/otvam/scisave

extra:
  recipe-maintainers:
    - otvam
